### ISSUE TITLE
Uncaught Symfony Namespace contains "/" but only characters in [-+_.A-Za-z0-9] are allowed.

### ISSUE THREAD

**Issue by ArdiArtani** [pgrimaud/instagram-user-feed#70] opened 2020-05-27 15:04 UTC
Hi,

I keep getting the error below for some reason. I am trying to find the issue and resolve it but thought you should know too.

`Fatal error: Uncaught Symfony\Component\Cache\Exception\InvalidArgumentException: Namespace contains "/" but only characters in [-+_.A-Za-z0-9] are allowed. in /home/demo/public_html/instagram/vendor/symfony/cache/Traits/FilesystemCommonTrait.php:35 Stack trace: #0 /home/demo/public_html/instagram/vendor/symfony/cache/Adapter/FilesystemAdapter.php(27): Symfony\Component\Cache\Adapter\FilesystemAdapter->init('/home/dem...', '/tmp/symfony-ca...') #1 /home/demo/public_html/index.php(23): Symfony\Component\Cache\Adapter\FilesystemAdapter->__construct('/home/dem...') #2 {main} thrown in /home/demo/public_html/instagram/vendor/symfony/cache/Traits/FilesystemCommonTrait.php on line 35`

Thanks,
AA

**Comment by pgrimaud** [comment] 2020-05-27 17:51
Hi @ArdiArtani 

I think the problem is with your FilesystemAdapter.

```php
$cachePool = new FilesystemAdapter('Instagram', 0, __DIR__ . '/../cache');
```

In my example, the first parameter is `Instagram` and can't contains a slash (/).

**Comment by ArdiArtani** [comment] 2020-05-27 18:48
Hi @pgrimaud 

I did try that but still, it wasn't working. Must be something else.

**Comment by pgrimaud** [comment] 2020-05-27 18:50
Can you paste your code?

**Comment by ArdiArtani** [comment] 2020-05-28 02:53
Here you go:

```
<?php
declare(strict_types=1);

use Instagram\Api;
use Instagram\Exception\InstagramException;

use Psr\Cache\CacheException;
use Symfony\Component\Cache\Adapter\FilesystemAdapter;

require realpath(dirname(__FILE__)) . '/lib/instagram/vendor/autoload.php';
$cachePool = new FilesystemAdapter('lib/instagram/cache');

try {
  $api = new Api($cachePool);
  $api->login($usernamex, $passwordx);
  $profile = $api->getProfile('robertdowneyjr');
} catch (InstagramException $e) {
  print_r($e->getMessage());
} catch (CacheException $e) {
  print_r($e->getMessage());
}
```

**Comment by ArdiArtani** [comment] 2020-05-28 03:09
@pgrimaud I managed to fix it but replacing the cache path **from**:

`$cachePool = new FilesystemAdapter('lib/instagram/cache');`
**to**
`$cachePool = new FilesystemAdapter('cache');`

But now I'm getting the same error as #69

**Comment by pareshsojitra** [comment] 2020-05-28 06:32
Here is the Working Code for WordPress :

use Instagram\Api;
use Symfony\Component\Cache\Adapter\FilesystemAdapter;

$cachePool = new FilesystemAdapter('Instagram', 0, WP_CONTENT_DIR . '/cache');

try {
	$api = new Api( $cachePool );
	$api->login( $user, $psw ); // optional, may be required on shared hosting
	$feed = $api->getProfile( $user );
	$feedmedia = array_slice( $feed->getMedias(), 0, $items );
	?>
	<ul>
		<?php
		/** @var \Instagram\Hydrator\Component\Media $media */
		foreach( $feedmedia as $media ) {
			?><li><a href="<?php echo esc_attr( $media->getLink() ); ?>" target="_blank"><img src="<?php echo esc_url( $media->getThumbnails()[$dimension]->src ); ?>" alt="<?php echo esc_attr( $media->getCaption() ); ?>"></a></li><?php
		}
		?>
	</ul>
	<?php
} catch( Exception $exception ) {
	?><div class="insta-error container alert alert-info" role="alert"><strong><?php esc_html_e('Instagram Configuration Error : ','SITEPREFIX'); ?></strong><?php print_r( $exception->getMessage() ); ?></div><?php
} catch( \GuzzleHttp\Exception\GuzzleException $e ) {
	?><div class="insta-error container alert alert-info" role="alert"><strong><?php esc_html_e('Instagram Configuration Error : ','SITEPREFIX'); ?></strong><?php print_r( $exception->getMessage() ); ?></div><?php
}

**Comment by pareshsojitra** [comment] 2020-05-28 06:39
Here is the Working Code for PHP :
```

try {
	
	/*
		$dimension
		0 - 150x150
		1 - 240x240
		2 - 320x320
		3 - 480x480
		4 - 640x640
	*/
	
	$user = '';
	$psw = '';
	$dimension = 0;
	$items = 10;

	$api = new Api( $cachePool );
	$api->login( $user, $psw ); // optional, may be required on shared hosting
	$feed = $api->getProfile( $user );
	$feedmedia = array_slice( $feed->getMedias(), 0, $items );
	?>
	<ul>
		<?php
		/** @var \Instagram\Hydrator\Component\Media $media */
		foreach( $feedmedia as $media ) {
			?><li><a href="<?php echo $media->getLink(); ?>" target="_blank"><img src="<?php echo $media->getThumbnails()[$dimension]->src; ?>" alt="<?php echo $media->getCaption(); ?>"></a></li><?php
		}
		?>
	</ul>
	<?php
} catch( Exception $exception ) {
	?><div class="insta-error container alert alert-info" role="alert"><strong>Instagram Configuration Error : </strong><?php print_r( $exception->getMessage() ); ?></div><?php
} catch( \GuzzleHttp\Exception\GuzzleException $e ) {
	?><div class="insta-error container alert alert-info" role="alert"><strong>Instagram Configuration Error : </strong><?php print_r( $exception->getMessage() ); ?></div><?php
}
```

**Comment by pgrimaud** [comment] 2020-05-28 20:22
> @pgrimaud I managed to fix it but replacing the cache path **from**:
> 
> `$cachePool = new FilesystemAdapter('lib/instagram/cache');`
> **to**
> `$cachePool = new FilesystemAdapter('cache');`

Cool! So I'm closing this issue 😄

**Closed by pgrimaud** 2020-05-28 20:22 UTC
Labels: support
