### ISSUE TITLE
Unable to extract JSON data

### ISSUE THREAD

**Issue by crgAdrian** [pgrimaud/instagram-user-feed#132] opened 2020-09-11 13:24 UTC
I've been getting this error for a few hours.

vendor/pgrimaud/instagram-user-feed/src/Instagram/Transport/HtmlProfileDataFeed.php:53

**Comment by pgrimaud** [comment] 2020-09-13 14:43
Could you give me the complete error?

**Comment by crgAdrian** [comment] 2020-09-14 12:47
https://gyazo.com/a6439c2bb407f3854d11c39b6b6ab0ab

**Comment by crgAdrian** [comment] 2020-09-14 17:36
POSIBLE:

The problem was when google asking a confirmation for location, security stuff.....

How I fixed "for now":

1. Deleting *cache folder* generated.
2. Confirm location Google (this was me)
3. Confirm location Instagram  (this was me)

**Comment by talhamubashar0012** [comment] 2020-09-15 13:50
Hi there, I'm facing the same issue on my dev server and the above mentioned fixes are not working for me as well

**Comment by aroy314** [comment] 2020-09-15 14:50
I'm experiencing the same issue on my production server, and being spammed on my Instagram Account to "confirm this was me"

**Comment by chOse** [comment] 2020-09-17 12:12
Exact same error for me today.

**Comment by gtapps** [comment] 2020-09-18 01:19
Same for me.

**Comment by gtapps** [comment] 2020-09-18 16:36
My problem was because my account got blocked for suspicious activity, I guess it's because of the crawling, IG must have implemented a check, basically all you have to do is relogin into your IG account and change your PW.

**Comment by paulprins** [comment] 2020-09-22 11:26
I had this too and needed to open that account in instagram to verify that it was me logging in.

**Comment by MehdiMJ1** [comment] 2020-09-22 13:29
I had the same problem and I have fixed now , it caused by detecting a **suspicious activity in your account**, so you must identify your entity by solving **Captcha** and **sending security code by phone number**,  that it is , just enter the official **Instagram** app and do these steps ..
My Pleasure To Help You 😁.

**Comment by talhamubashar0012** [comment] 2020-10-06 13:53
> I had the same problem and I have fixed now , it caused by detecting a **suspicious activity in your account**, so you must identify your entity by solving **Captcha** and **sending security code by phone number**, that it is , just enter the official **Instagram** app and do these steps ..
> My Pleasure To Help You 😁.

None of this worked for me. Tried several time to verify but its not working. Does anyone of you guys have a better solution. It will be helpful

**Comment by PrasadBroo** [comment] 2020-10-26 12:14
im also facing same problem on production server

**Comment by pgrimaud** [comment] 2020-11-05 22:18
@PrasadBroo could contact me on Twitter by DM to try to find a solution? https://twitter.com/pgrimaud_

**Comment by curruwilla** [comment] 2020-11-13 21:33
Unable to extract JSON data

Is it happening to me too, any solution?

**Comment by CodingAnonymous** [comment] 2020-11-16 09:55
I have the error, too. Is there any solution yet?

**Comment by xdnan7** [comment] 2020-11-23 03:05
I had the same problem too. Just logon to your dummy instagram account, go to menu Setting -> Login activity -> Confirm your login.

**Closed** 2020-12-26 05:13 UTC
Labels: need-investigations, question, support, wontfix

**Comment by davpirelli** [comment] 2021-09-10 07:43
Still have the same problem but confirming location/captcha/sms doesn't work for me..still getting Unable to extract JSON data

**Comment by gergel0304** [comment] 2021-10-12 08:40
Cleaning /cache folder help me
