### ISSUE TITLE
Response for media query is changed - throws Undefined property: stdClass::$graphql 

### ISSUE THREAD

**Issue by andreifiroiu** [pgrimaud/instagram-user-feed#268] opened 2022-02-05 18:47 UTC
**Version(s) affected**: 6.*

**Description**  
The response for detailed media query changed and doesn't return a grapql property anymore, those affecting both getMediaDetailedByShortCode() and getMediaDetailed() methods.

**How to reproduce**  
Running any of these 2 examples:
https://github.com/pgrimaud/instagram-user-feed/blob/master/examples/media-detailed-by-shortcode.php
https://github.com/pgrimaud/instagram-user-feed/blob/master/examples/media-detailed.php

![Screenshot 2022-02-05 at 20-47-09 🧨 Undefined property stdClass $graphql](https://user-images.githubusercontent.com/4728003/152654820-e8093eec-d942-4bac-9abc-2afa4e7c6dff.png)

![Screenshot 2022-02-05 at 20 37 09](https://user-images.githubusercontent.com/4728003/152654792-8b8f2ee5-2502-4b05-a23b-221dec648b16.png)

**Comment by cookieguru** [comment] 2022-02-11 04:58
Is this a duplicate of #266?

**Closed** 2022-03-17 10:52 UTC
Labels: wontfix, need-investigations
